site_name: iclr2025_mbr_uncertainty
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: iclr2025_mbr_uncertainty
      handlers:
        python:
          options:
            docstring_style: numpy